name: Periodic URL health check

on:
  schedule:
    - cron: '0 12 * * *' # run daily at 12:00

  # enable to be triggered manually
  workflow_dispatch:

jobs:
  check_health:
    runs-on: ubuntu-latest
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v4
        with:
          url: https://pokedex-t5zu.onrender.com
          max-attempts: 2
